# Generated by Django 5.1.4 on 2025-01-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0002_register_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='newcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=6)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_children_photos/')),
                ('last_seen_date', models.DateTimeField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('suspect_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_description', models.TextField(blank=True, null=True)),
                ('vehicle_info', models.CharField(blank=True, max_length=255, null=True)),
                ('authorities_contacted', models.BooleanField(default=False)),
                ('search_efforts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
