# Generated by Django 5.1.4 on 2025-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0003_newcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=7),
        ),
    ]
