# Generated by Django 5.1.4 on 2025-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0004_newcase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('hair_color', models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('grey', 'Grey')], max_length=6, null=True)),
                ('distinctive_marks', models.TextField(blank=True, null=True)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_date', models.DateField()),
                ('last_known_clothing', models.TextField(blank=True, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('information_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
