# Generated by Django 5.1.4 on 2025-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0005_childlocator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childlocator',
            name='nationality',
        ),
        migrations.AddField(
            model_name='childlocator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='child_locator_images/'),
        ),
    ]
