# Generated by Django 5.1.4 on 2025-01-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0006_remove_childlocator_nationality_childlocator_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childlocator',
            old_name='information_confirmed',
            new_name='accept',
        ),
    ]
