# Generated by Django 5.1.4 on 2025-02-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0007_rename_information_confirmed_childlocator_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childlocator',
            name='image',
            field=models.ImageField(default=1, upload_to='child_locator_images/'),
            preserve_default=False,
        ),
    ]
