# Generated by Django 5.1.7 on 2025-03-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('case_photo', models.ImageField(blank=True, null=True, upload_to='case_photos/')),
                ('child_name', models.CharField(max_length=255)),
                ('child_age', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('date_disappearance', models.DateField()),
                ('description', models.TextField()),
                ('suspected_causes', models.CharField(blank=True, max_length=255, null=True)),
                ('who_involved', models.CharField(blank=True, max_length=255, null=True)),
                ('tools_methods', models.CharField(blank=True, max_length=255, null=True)),
                ('found_location', models.TextField()),
                ('who_found', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_wellbeing', models.TextField(blank=True, null=True)),
                ('legal_actions', models.TextField(blank=True, null=True)),
                ('submitted_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='childlocator',
            name='additional_contact',
        ),
        migrations.AddField(
            model_name='childlocator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
