# Generated by Django 5.1.7 on 2025-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0010_childrecoverycase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childlocator',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
