# Generated by Django 5.1.6 on 2025-03-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0011_childlocator_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childrecoverycase',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='childrecoverycase',
            name='case_photo',
        ),
        migrations.RemoveField(
            model_name='childrecoverycase',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='childrecoverycase',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='childrecoverycase',
            name='location',
        ),
        migrations.AddField(
            model_name='childrecoverycase',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childmissingwebapp.newcase'),
        ),
        migrations.AddField(
            model_name='childrecoverycase',
            name='childloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childmissingwebapp.childlocator'),
        ),
    ]
