# Generated by Django 5.1.5 on 2025-12-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingwebapp', '0012_remove_childrecoverycase_case_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploaded_videos/')),
                ('matched_child', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
